# Generated by Django 4.0.3 on 2022-04-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_patient_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
