# Generated by Django 4.0.3 on 2022-04-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_medication_sig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='SIG',
            field=models.CharField(max_length=300),
        ),
    ]
