# Generated by Django 4.0.3 on 2022-10-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_medication_sig'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='tobacco_start',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='tobacco_status',
            field=models.CharField(default='Never', max_length=50),
        ),
    ]
