# Generated by Django 4.0.3 on 2022-10-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_patient_tobacco_start_patient_tobacco_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='tobacco_end',
            field=models.IntegerField(null=True),
        ),
    ]
